In [ ]:
import numpy as np

In [ ]:
s = np.array([
[1, 2, 3, 4, 5, 6, 7, 8, 9],
[2, 3, 4, 5, 6, 7, 8, 9, 1],
[3, 4, 5, 6, 7, 8, 9, 1, 2],

[4, 5, 6, 7, 8, 9, 1, 2, 3],
[5, 6, 7, 8, 9, 1, 2, 3, 4],
[6, 7, 8, 9, 1, 2, 3, 4, 5],

[7, 8, 9, 1, 2, 3, 4, 5, 6],
[8, 9, 1, 2, 3, 4, 5, 6, 7],
[9, 1, 2, 3, 4, 5, 6, 7, 8]
])

In [ ]:


b = np.sum(s, axis=1)
for i in b:
    if i != 45:
        print("sudokuis not valid")
        break
else:
    print("sudokuis valid")

# Calculate column sums
c = np.sum(s, axis=0)
for i in c:
    if i != 45:
        print("sudokuis not valid")
        break
else:
    print("sudokuis valid")

sudokuis valid
sudokuis valid


In [ ]:
s[0:3,0:3]

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [ ]:
s[0:3,3:6]

array([[4, 5, 6],
       [5, 6, 7],
       [6, 7, 8]])

In [ ]:
for i in range(0,9,3):
  for j in range(0,9,3):
    n = (s[i:i+3,j:j+3])
    print(n.sum())

27
54
54
54
54
27
54
27
54


In [ ]:
import numpy as np
#[age,math marks,science marks]
data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,90,85]
])

In [ ]:
data.shape

(5, 3)

In [ ]:
np.mean(data[:,0])

np.float64(18.4)

as a matrix


In [ ]:
data[0:5 ,1:2]

array([[85],
       [92],
       [76],
       [65],
       [90]])

as a vector


In [ ]:
data[:,1]

array([85, 92, 76, 65, 90])

In [ ]:
np.max(data[:,2])

np.int64(95)

In [ ]:
data [data[:,1]>90]

array([[19, 92, 88]])

In [ ]:
M = data[:,1] +  5
M

array([90, 97, 81, 70, 95])

In [ ]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65, 70],
       [20, 90, 85]])